// 全局变量补全（内置对象名称）
export const globalCompletions = [
    {label: 'Math', type: 'class', detail: 'object', info: '数学运算对象'},
    {label: 'console', type: 'class', detail: 'object', info: '控制台对象'},
    {label: 'JSON', type: 'class', detail: 'object', info: 'JSON 解析和序列化'},
    {label: 'Array', type: 'class', detail: 'constructor', info: '数组构造函数'},
    {label: 'Object', type: 'class', detail: 'constructor', info: '对象构造函数'},
    {label: 'String', type: 'class', detail: 'constructor', info: '字符串构造函数'},
    {label: 'Number', type: 'class', detail: 'constructor', info: '数字构造函数'},
    {label: 'Boolean', type: 'class', detail: 'constructor', info: '布尔构造函数'},
    {label: 'Date', type: 'class', detail: 'constructor', info: '日期构造函数'},
    {label: 'RegExp', type: 'class', detail: 'constructor', info: '正则表达式构造函数'},
    {label: 'Promise', type: 'class', detail: 'constructor', info: 'Promise 构造函数'},
    {label: 'Map', type: 'class', detail: 'constructor', info: 'Map 构造函数'},
    {label: 'Set', type: 'class', detail: 'constructor', info: 'Set 构造函数'},
    {label: 'WeakMap', type: 'class', detail: 'constructor', info: 'WeakMap 构造函数'},
    {label: 'WeakSet', type: 'class', detail: 'constructor', info: 'WeakSet 构造函数'},
    {
        label: 'setTimeout',
        type: 'function',
        detail: '(handler: Function, timeout?: number, ...args: any[]) => number',
        info: '延迟执行函数'
    },
    {
        label: 'setInterval',
        type: 'function',
        detail: '(handler: Function, timeout?: number, ...args: any[]) => number',
        info: '定时执行函数'
    },
    {label: 'clearTimeout', type: 'function', detail: '(id: number) => void', info: '清除延迟执行'},
    {label: 'clearInterval', type: 'function', detail: '(id: number) => void', info: '清除定时执行'},
    {
        label: 'fetch',
        type: 'function',
        detail: '(input: RequestInfo, init?: RequestInit) => Promise<Response>',
        info: '发起网络请求'
    },
    {label: 'parseInt', type: 'function', detail: '(string: string, radix?: number) => number', info: '解析整数'},
    {label: 'parseFloat', type: 'function', detail: '(string: string) => number', info: '解析浮点数'},
    {label: 'isNaN', type: 'function', detail: '(value: any) => boolean', info: '判断是否为 NaN'},
    {label: 'isFinite', type: 'function', detail: '(value: any) => boolean', info: '判断是否为有限数'},
    {label: 'encodeURI', type: 'function', detail: '(uri: string) => string', info: '编码 URI'},
    {label: 'decodeURI', type: 'function', detail: '(uri: string) => string', info: '解码 URI'},
    {label: 'encodeURIComponent', type: 'function', detail: '(component: string) => string', info: '编码 URI 组件'},
    {label: 'decodeURIComponent', type: 'function', detail: '(component: string) => string', info: '解码 URI 组件'},

    {label: 'document', type: 'class', detail: 'Document', info: '文档对象，操作 DOM 的入口'},
    {label: 'localStorage', type: 'class', detail: 'Storage', info: '本地存储对象，持久化存储数据'},
    {label: 'sessionStorage', type: 'class', detail: 'Storage', info: '会话存储对象，仅在当前会话有效'},
    {label: 'location', type: 'class', detail: 'Location', info: '位置对象，获取和操作当前 URL'},

    // 相关的补充对象
    {label: 'window', type: 'class', detail: 'Window', info: '浏览器窗口对象'},
    {label: 'history', type: 'class', detail: 'History', info: '历史记录对象'},
    {label: 'navigator', type: 'class', detail: 'Navigator', info: '浏览器信息对象'},
    {label: 'screen', type: 'class', detail: 'Screen', info: '屏幕信息对象'},

    {label: 'self', type: 'class', detail: 'Window', info: '当前窗口的引用'},
    {label: 'top', type: 'class', detail: 'Window', info: '最顶层窗口的引用'},
    {label: 'parent', type: 'class', detail: 'Window', info: '父窗口的引用'},

    // 新增全局对象
    {label: 'atob', type: 'function', detail: '(encodedData: string) => string', info: '解码 Base64 编码的字符串'},
    {label: 'btoa', type: 'function', detail: '(stringToEncode: string) => string', info: '将字符串编码为 Base64 格式'},
    {label: 'encodeURI', type: 'function', detail: '(uri: string) => string', info: '编码 URI'},
    {label: 'decodeURI', type: 'function', detail: '(encodedURI: string) => string', info: '解码 URI'},
    {label: 'encodeURIComponent', type: 'function', detail: '(component: string) => string', info: '编码 URI 组件'},
    {
        label: 'decodeURIComponent',
        type: 'function',
        detail: '(encodedComponent: string) => string',
        info: '解码 URI 组件'
    },
    {label: 'NaN', type: 'constant', detail: 'number', info: 'Not-a-Number'},
    {label: 'Infinity', type: 'constant', detail: 'number', info: '无穷大'},
    {label: 'undefined', type: 'constant', detail: 'undefined', info: '未定义'},
    {label: 'globalThis', type: 'class', detail: 'Window', info: '全局对象'},
    {label: 'AbortController', type: 'class', detail: 'AbortController', info: '中止控制器'},
    {label: 'IntersectionObserver', type: 'class', detail: 'IntersectionObserver', info: '交叉观察器'},
    {label: 'MutationObserver', type: 'class', detail: 'MutationObserver', info: '突变观察器'},
    {label: 'ResizeObserver', type: 'class', detail: 'ResizeObserver', info: '尺寸观察器'},
    {label: 'WebSocket', type: 'class', detail: 'WebSocket', info: 'WebSocket 连接'},
    {label: 'EventSource', type: 'class', detail: 'EventSource', info: 'SSE 客户端'},
    {label: 'File', type: 'class', detail: 'File', info: '文件对象'},
    {label: 'FileReader', type: 'class', detail: 'FileReader', info: '文件读取器'},
    {label: 'Blob', type: 'class', detail: 'Blob', info: '二进制大对象'},
    {label: 'URL', type: 'class', detail: 'URL', info: 'URL 对象'},
    {label: 'URLSearchParams', type: 'class', detail: 'URLSearchParams', info: 'URL 查询参数'},
    {label: 'FormData', type: 'class', detail: 'FormData', info: '表单数据'},
    {label: 'crypto', type: 'class', detail: 'Crypto', info: '加密 API'},
    {label: 'BroadcastChannel', type: 'class', detail: 'BroadcastChannel', info: '广播通道'},
    {label: 'performance', type: 'class', detail: 'Performance', info: '性能 API'},
    {label: 'Proxy', type: 'class', detail: 'Proxy', info: '代理对象'},
    {label: 'Reflect', type: 'class', detail: 'Reflect', info: '反射 API'},
    {label: 'Symbol', type: 'class', detail: 'Symbol', info: '符号类型'},
    {label: 'BigInt', type: 'class', detail: 'BigInt', info: '大整数'},
    {label: 'Intl', type: 'class', detail: 'Intl', info: '国际化 API'},
    {label: 'Worker', type: 'class', detail: 'Worker', info: 'Web Worker'},
    {label: 'Notification', type: 'class', detail: 'Notification', info: '通知 API'},
    {label: 'ReadableStream', type: 'class', detail: 'ReadableStream', info: '可读流'},
    {label: 'WritableStream', type: 'class', detail: 'WritableStream', info: '可写流'},
    {label: 'Clipboard', type: 'class', detail: 'Clipboard', info: '剪贴板 API'},
    {label: 'scheduler', type: 'class', detail: 'Scheduler', info: '调度器'},
    {label: 'queueMicrotask', type: 'function', detail: '(callback: Function) => void', info: '添加微任务'},
    {label: 'import', type: 'function', detail: '(specifier: string) => Promise<any>', info: '动态导入模块'}
];